---
title: "GIS Exercises Week 4"
author: "J.Blondeau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
options(width = 750)
```

This week you will be working on a project exclusively in the St. Thomas East End Reserve (STEER).  You will use some new tools and some tools you used last week to complete all the questions.   

***
## Data
Most the data is the class exercise folder you already downloaded...

3 shapefiles

- STTSTJ_NOAA_Habitiat_Map
- STEER_Boundary
- ProposedMooringLocations

1 raster dataset

- steer_1m

1 .csv 

* I forgot to add this dataset to the 'Class Exercise Data' folder.  Please download this specific file from our shared GDrive.

- sttstj_ncrmp_hab.csv

***


### Part 1
1. Import all the data into your project directory (3 shapefiles and raster dataset).  
2. Create a shapefile (point) from the sttstj_ncrmp_hab.csv
3. Clip the NOAA habitat map feature using the STEER boundary feature.  We only want to work with data inside the STEER reserve.
4. Change the symbology of this new layer to show unique colors for each 'HABITAT'.
5. What is the area (m^2^) of "Coral Reef and Colonized Hardbottom" habitat classification within STEER?
6. Select all the NCRMP sites sampled within STEER and create a new layer from selection.
7. Change the symbology to 'graduated symbols' on the PCT_CORAL field (diver estimated %coral cover).  Adjust the parameters to show NCRMP sites inside STEER with varying degrees of live coral cover.

##### Bonus
8. Create a hillshade of the 2 meter raster dataset.  Make multiple hillshades using different parameters (Azimuth, Altitude, Z Factor) so see the differences. 
9. In the contents pane, place the hillshade raster on top of the bathymetry layer.  Adjust the symbology of the depth raster and adjust the hillshade 'Layer Blend' modes until you like the outcome.
<br><br>

### Part 2

In this fictional scenario, you are tasked with selecting from a large list of mooring locations inside STEER from the  ProposedMooringLocations shapefile all the locations that are at least 50m away from any mapped coral reef or colonized hardbottom.  There are multiple ways you could solve this task, but I would like for you to use the buffer tool.  DPNR only has enough funding for 5 moorings.  Which 5 would you propose DPNR install?  Adjust the symbology for all the layers to make it clear which locations are appropriate and which 5 locations you are proposing as ideal.  

##### Bonus

Along with mooring locations being at least 50m away from mapped coral reef or colonized hardbottom, mooring locations must be shallower than 30ft depth.  Propose new 'best' site locations.  Hint..."Extract Values to Points", or "Extract Multi Values to Points" (What is the difference?)










